version: "3.8"

services:
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_CONSOLE_ADDRESS: ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
  init-minio:
    image: minio/mc
    container_name: init-minio
    depends_on:
      - minio
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set myminio http://minio:9000 minio minio123;
        mc mb myminio/freelay
        mc policy set public myminio/freelay
