version: "3.8"

services:
  swag:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
    environment:
      SWAGGER_JSON: /tmp/swagger.yaml
